# Generated by Django 5.0.3 on 2024-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0001_initial'),
        ('Web_inher', '0003_remove_gallery_web_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_log',
            name='category_web_model',
            field=models.ManyToManyField(to='Web_inher.category_web'),
        ),
        migrations.AddField(
            model_name='web_log',
            name='tag',
            field=models.ManyToManyField(related_name='weblog_tag', to='Web_inher.tag'),
        ),
    ]
