# Generated by Django 5.0.3 on 2024-05-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0002_web_log_category_web_model_web_log_tag'),
        ('Web_inher', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_log',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_inher.gallery'),
        ),
    ]
