# Generated by Django 5.0.3 on 2024-05-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0003_web_log_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_discription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seasionone', models.CharField(max_length=200)),
                ('discription_seasionone', models.TextField()),
                ('title_seasiontwo', models.CharField(max_length=200)),
                ('discription_seasiontwo', models.TextField()),
                ('title_seasiontree', models.CharField(max_length=200)),
                ('discription_seasiontree', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='web_log',
            name='extra_discription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebLog.more_discription'),
        ),
    ]
