# Generated by Django 5.0.3 on 2024-06-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0006_web_log_comment'),
        ('Web_inher', '0007_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_log',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_inher.gender'),
        ),
    ]
