# Generated by Django 5.0.3 on 2024-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0007_web_log_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_log',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
