# Generated by Django 5.0.3 on 2024-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0010_web_log_is_active'),
        ('Web_inher', '0009_alter_tag_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_log',
            name='category_web_model',
            field=models.ManyToManyField(to='Web_inher.category_web'),
        ),
    ]
