# Generated by Django 5.0.3 on 2024-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0011_alter_web_log_category_web_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_log',
            name='rateofblog',
            field=models.IntegerField(default=0),
        ),
    ]
