# Generated by Django 5.0.3 on 2024-06-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0012_web_log_rateofblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_log',
            name='rateofblog',
        ),
    ]
