# Generated by Django 5.0.3 on 2024-06-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0014_rate_of_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_of_blog',
            name='weblod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_set', to='WebLog.web_log'),
        ),
    ]
