# Generated by Django 5.0.3 on 2024-06-19 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0016_web_log_satisfaction_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_of_blog',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='web_log',
            name='satisfaction_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
