# Generated by Django 5.0.3 on 2024-05-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLog', '0001_initial'),
        ('Web_inher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='web_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebLog.web_log'),
        ),
    ]
