# Generated by Django 5.0.3 on 2024-05-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_inher', '0002_gallery_web_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='web_id',
        ),
    ]
