# Generated by Django 5.0.3 on 2024-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_inher', '0003_remove_gallery_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/weblog/%Y/%m/%d'),
        ),
    ]
