# Generated by Django 5.0.3 on 2024-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_inher', '0007_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='upload/weblog/%Y/%m/%d'),
        ),
    ]
