# Generated by Django 5.0.3 on 2024-06-01 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Welcome_message_text', models.CharField(max_length=200)),
                ('Title_description', models.CharField(max_length=200)),
                ('Main_description', models.TextField()),
                ('part1_description', models.CharField(blank=True, max_length=200, null=True)),
                ('part1_body', models.CharField(blank=True, max_length=200, null=True)),
                ('part2_description', models.CharField(blank=True, max_length=200, null=True)),
                ('part2_body', models.CharField(blank=True, max_length=200, null=True)),
                ('part3_description', models.CharField(blank=True, max_length=200, null=True)),
                ('part3_body', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.CharField(max_length=200)),
                ('Address_map', models.URLField()),
                ('Logo_web', models.ImageField(upload_to='upload/Site_Setting/logo')),
                ('Main_photo', models.ImageField(upload_to='upload/Site_Setting/Main_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Text_massage', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
