# Generated by Django 5.0.3 on 2024-06-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='part1_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='part2_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='part3_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
