# Generated by Django 5.0.3 on 2024-06-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0002_alter_about_us_part1_body_alter_about_us_part2_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='Image_for_About',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Site_Setting/About'),
        ),
    ]
