# Generated by Django 5.0.3 on 2024-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0003_about_us_image_for_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_img', models.ImageField(upload_to='upload/Site_Setting/Photo_page')),
                ('list_weblog_img', models.ImageField(upload_to='upload/Site_Setting/Photo_page')),
                ('contact_us_img', models.ImageField(upload_to='upload/Site_Setting/Photo_page')),
                ('make_blog_img', models.ImageField(upload_to='upload/Site_Setting/Photo_page')),
            ],
        ),
    ]
