# Generated by Django 5.0.3 on 2024-06-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0004_photo_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_page',
            name='text_for_listweblog',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='text_wellcome_firstpage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
