# Generated by Django 5.0.3 on 2024-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0005_photo_page_text_for_listweblog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='about_website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='link_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='link_telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='link_x',
            field=models.URLField(blank=True, null=True),
        ),
    ]
