# Generated by Django 5.0.3 on 2024-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0006_site_setting_about_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='text_for_rule',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
