# Generated by Django 5.0.3 on 2024-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0007_site_setting_text_for_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='upload/Site_Setting/Team_about')),
                ('job', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='about_website',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='link_instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='link_telegram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='link_x',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='text_for_rule',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='text_wellcome_firstpage',
            field=models.CharField(max_length=200),
        ),
    ]
