# Generated by Django 5.0.3 on 2024-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0008_team_about_alter_site_setting_about_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
