# Generated by Django 5.0.3 on 2024-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0009_contact_us_response_contact_us_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('visited_ip', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='Address_map',
            field=models.URLField(max_length=500),
        ),
    ]
