# Generated by Django 5.0.3 on 2024-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0011_alter_uservisit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
