# Generated by Django 5.0.3 on 2024-06-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLogSetting', '0012_alter_uservisit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
