# Generated by Django 5.0.3 on 2024-03-20 06:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='autentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image_pro', models.ImageField(blank=True, max_length=500, null=True, upload_to='upload/profile/% Y/% m/% d/')),
                ('main_location', models.CharField(choices=[('1', 'اردبیل'), ('2', 'اصفهان'), ('3', 'البرز'), ('4', 'ایلام'), ('5', 'آذربایجان شرقی'), ('6', 'آذربایجان غربی'), ('7', 'بوشهر'), ('8', 'تهران'), ('9', 'چهارمحال وبختیاری'), ('10', 'خراسان جنوبی'), ('11', 'خراسان رضوی'), ('12', 'خراسان شمالی'), ('13', 'خوزستان'), ('14', 'زنجان'), ('15', 'سمنان'), ('16', 'سیستان وبلوچستان'), ('17', 'فارس'), ('18', 'قزوین'), ('19', 'قم'), ('20', 'کردستان'), ('21', 'کرمان'), ('22', 'کرمانشاه'), ('23', 'کهگیلویه وبویراحمد'), ('24', 'گلستان'), ('25', 'گیلان'), ('26', 'لرستان'), ('27', 'مازندران'), ('28', 'مرکزی'), ('29', 'هرمزگان'), ('30', 'همدان'), ('31', 'یزد')], max_length=100)),
                ('location', models.CharField(choices=[], max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('date_birth', models.DateField()),
                ('about_user', models.TextField(max_length=500)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
