# Generated by Django 5.0.3 on 2024-03-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentication',
            name='about_user',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='location',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='main_location',
            field=models.CharField(blank=True, choices=[('1', 'اردبیل'), ('2', 'اصفهان'), ('3', 'البرز'), ('4', 'ایلام'), ('5', 'آذربایجان شرقی'), ('6', 'آذربایجان غربی'), ('7', 'بوشهر'), ('8', 'تهران'), ('9', 'چهارمحال وبختیاری'), ('10', 'خراسان جنوبی'), ('11', 'خراسان رضوی'), ('12', 'خراسان شمالی'), ('13', 'خوزستان'), ('14', 'زنجان'), ('15', 'سمنان'), ('16', 'سیستان وبلوچستان'), ('17', 'فارس'), ('18', 'قزوین'), ('19', 'قم'), ('20', 'کردستان'), ('21', 'کرمان'), ('22', 'کرمانشاه'), ('23', 'کهگیلویه وبویراحمد'), ('24', 'گلستان'), ('25', 'گیلان'), ('26', 'لرستان'), ('27', 'مازندران'), ('28', 'مرکزی'), ('29', 'هرمزگان'), ('30', 'همدان'), ('31', 'یزد')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
