# Generated by Django 5.0.3 on 2024-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0002_alter_autentication_about_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autentication',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autentication',
            name='verify_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='main_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
