# Generated by Django 5.0.3 on 2024-05-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0003_autentication_is_verify_autentication_verify_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentication',
            name='image_pro',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile/%Y/%m/%d'),
        ),
    ]
