# Generated by Django 5.0.3 on 2024-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0004_alter_autentication_image_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentication',
            name='image_pro',
            field=models.ImageField(blank=True, default='upload/profile/defult_pro.png', null=True, upload_to='upload/profile/%Y/%m/%d'),
        ),
    ]
