# Generated by Django 5.0.3 on 2024-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0005_alter_autentication_image_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentication',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email adress'),
        ),
    ]
