# Generated by Django 5.0.3 on 2024-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Setting', '0006_alter_autentication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
